#!/bin/bash 

#example of using for loop

#example 1
for car in Chevrolet Tyota Nissan Tyota Tesla Honda 4Runner Ferrari BMW 
do 
		echo"our favorite cars are $car" 
		echo"The length of the car is: ${#car} "


done 

#example 2

for (( x=1; x<=10; x++ ))
do 
	echo "iterration : $x"
	sleep 0.3
done

#example 

for (( x=100; x>=10; x=x-2 ))
do 
	echo "itertation: $x"
done

#example 3. Looping over the arguments
for arg in $* 

	echo 

